### YamlMime:ManagedReference
items:
- uid: RedisKit.Models.CircuitBreakerSettings
  commentId: T:RedisKit.Models.CircuitBreakerSettings
  id: CircuitBreakerSettings
  parent: RedisKit.Models
  children:
  - RedisKit.Models.CircuitBreakerSettings.BreakDuration
  - RedisKit.Models.CircuitBreakerSettings.Enabled
  - RedisKit.Models.CircuitBreakerSettings.FailureThreshold
  - RedisKit.Models.CircuitBreakerSettings.FailureWindow
  - RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
  langs:
  - csharp
  - vb
  name: CircuitBreakerSettings
  nameWithType: CircuitBreakerSettings
  fullName: RedisKit.Models.CircuitBreakerSettings
  type: Class
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: CircuitBreakerSettings
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 5
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Circuit breaker configuration
  example: []
  syntax:
    content: public class CircuitBreakerSettings
    content.vb: Public Class CircuitBreakerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: RedisKit.Models.CircuitBreakerSettings.Enabled
  commentId: P:RedisKit.Models.CircuitBreakerSettings.Enabled
  id: Enabled
  parent: RedisKit.Models.CircuitBreakerSettings
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: CircuitBreakerSettings.Enabled
  fullName: RedisKit.Models.CircuitBreakerSettings.Enabled
  type: Property
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: Enabled
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 10
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Enable circuit breaker pattern
  example: []
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: RedisKit.Models.CircuitBreakerSettings.Enabled*
- uid: RedisKit.Models.CircuitBreakerSettings.FailureThreshold
  commentId: P:RedisKit.Models.CircuitBreakerSettings.FailureThreshold
  id: FailureThreshold
  parent: RedisKit.Models.CircuitBreakerSettings
  langs:
  - csharp
  - vb
  name: FailureThreshold
  nameWithType: CircuitBreakerSettings.FailureThreshold
  fullName: RedisKit.Models.CircuitBreakerSettings.FailureThreshold
  type: Property
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: FailureThreshold
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 15
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Number of failures before opening circuit
  example: []
  syntax:
    content: public int FailureThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property FailureThreshold As Integer
  overload: RedisKit.Models.CircuitBreakerSettings.FailureThreshold*
- uid: RedisKit.Models.CircuitBreakerSettings.FailureWindow
  commentId: P:RedisKit.Models.CircuitBreakerSettings.FailureWindow
  id: FailureWindow
  parent: RedisKit.Models.CircuitBreakerSettings
  langs:
  - csharp
  - vb
  name: FailureWindow
  nameWithType: CircuitBreakerSettings.FailureWindow
  fullName: RedisKit.Models.CircuitBreakerSettings.FailureWindow
  type: Property
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: FailureWindow
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 20
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Time window for counting failures
  example: []
  syntax:
    content: public TimeSpan FailureWindow { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property FailureWindow As TimeSpan
  overload: RedisKit.Models.CircuitBreakerSettings.FailureWindow*
- uid: RedisKit.Models.CircuitBreakerSettings.BreakDuration
  commentId: P:RedisKit.Models.CircuitBreakerSettings.BreakDuration
  id: BreakDuration
  parent: RedisKit.Models.CircuitBreakerSettings
  langs:
  - csharp
  - vb
  name: BreakDuration
  nameWithType: CircuitBreakerSettings.BreakDuration
  fullName: RedisKit.Models.CircuitBreakerSettings.BreakDuration
  type: Property
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: BreakDuration
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 25
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Duration to keep circuit open
  example: []
  syntax:
    content: public TimeSpan BreakDuration { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property BreakDuration As TimeSpan
  overload: RedisKit.Models.CircuitBreakerSettings.BreakDuration*
- uid: RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
  commentId: P:RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
  id: SuccessThreshold
  parent: RedisKit.Models.CircuitBreakerSettings
  langs:
  - csharp
  - vb
  name: SuccessThreshold
  nameWithType: CircuitBreakerSettings.SuccessThreshold
  fullName: RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
  type: Property
  source:
    remote:
      path: RedisKit/Models/CircuitBreakerSettings.cs
      branch: master
      repo: https://github.com/ersintarhan/RedisKit.git
    id: SuccessThreshold
    path: RedisKit/Models/CircuitBreakerSettings.cs
    startLine: 30
  assemblies:
  - RedisKit
  namespace: RedisKit.Models
  summary: Number of successful calls to close circuit
  example: []
  syntax:
    content: public int SuccessThreshold { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property SuccessThreshold As Integer
  overload: RedisKit.Models.CircuitBreakerSettings.SuccessThreshold*
references:
- uid: RedisKit.Models
  commentId: N:RedisKit.Models
  href: RedisKit.html
  name: RedisKit.Models
  nameWithType: RedisKit.Models
  fullName: RedisKit.Models
  spec.csharp:
  - uid: RedisKit
    name: RedisKit
    href: RedisKit.html
  - name: .
  - uid: RedisKit.Models
    name: Models
    href: RedisKit.Models.html
  spec.vb:
  - uid: RedisKit
    name: RedisKit
    href: RedisKit.html
  - name: .
  - uid: RedisKit.Models
    name: Models
    href: RedisKit.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: RedisKit.Models.CircuitBreakerSettings.Enabled*
  commentId: Overload:RedisKit.Models.CircuitBreakerSettings.Enabled
  href: RedisKit.Models.CircuitBreakerSettings.html#RedisKit_Models_CircuitBreakerSettings_Enabled
  name: Enabled
  nameWithType: CircuitBreakerSettings.Enabled
  fullName: RedisKit.Models.CircuitBreakerSettings.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: RedisKit.Models.CircuitBreakerSettings.FailureThreshold*
  commentId: Overload:RedisKit.Models.CircuitBreakerSettings.FailureThreshold
  href: RedisKit.Models.CircuitBreakerSettings.html#RedisKit_Models_CircuitBreakerSettings_FailureThreshold
  name: FailureThreshold
  nameWithType: CircuitBreakerSettings.FailureThreshold
  fullName: RedisKit.Models.CircuitBreakerSettings.FailureThreshold
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: RedisKit.Models.CircuitBreakerSettings.FailureWindow*
  commentId: Overload:RedisKit.Models.CircuitBreakerSettings.FailureWindow
  href: RedisKit.Models.CircuitBreakerSettings.html#RedisKit_Models_CircuitBreakerSettings_FailureWindow
  name: FailureWindow
  nameWithType: CircuitBreakerSettings.FailureWindow
  fullName: RedisKit.Models.CircuitBreakerSettings.FailureWindow
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: RedisKit.Models.CircuitBreakerSettings.BreakDuration*
  commentId: Overload:RedisKit.Models.CircuitBreakerSettings.BreakDuration
  href: RedisKit.Models.CircuitBreakerSettings.html#RedisKit_Models_CircuitBreakerSettings_BreakDuration
  name: BreakDuration
  nameWithType: CircuitBreakerSettings.BreakDuration
  fullName: RedisKit.Models.CircuitBreakerSettings.BreakDuration
- uid: RedisKit.Models.CircuitBreakerSettings.SuccessThreshold*
  commentId: Overload:RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
  href: RedisKit.Models.CircuitBreakerSettings.html#RedisKit_Models_CircuitBreakerSettings_SuccessThreshold
  name: SuccessThreshold
  nameWithType: CircuitBreakerSettings.SuccessThreshold
  fullName: RedisKit.Models.CircuitBreakerSettings.SuccessThreshold
