name: Build and Deploy Documentation

on:
  # Manual trigger
  workflow_dispatch:
  
  # Auto-deploy on releases
  release:
    types: [published]
  
  # Auto-deploy when docs are changed
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'docfx.json'
      - 'toc.yml'
      - 'index.md'
      - 'articles/**'
      - '.github/workflows/docs.yml'
  
  # Weekly scheduled build to keep docs fresh
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Install DocFX
      run: dotnet tool install -g docfx
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build project
      run: dotnet build RedisKit -c Release
    
    - name: Generate API metadata
      run: docfx metadata docfx.json
    
    - name: Build documentation
      run: docfx build docfx.json
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4